### ISSUE TITLE
STT Class Configuration

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/zzz-old-ovos-utils#56]
Is there any other interest in or reason against adding an optional config parameter being added to the base STT class (like TTS has).

This would diverge from Mycroft but retain compatibility while also allowing a non-Mycroft configuration to be used.

**Comment by NeonDaniel** [comment]
https://github.com/OpenVoiceOS/ovos_utils/blob/b40e7d618a1746ffbf286caaa5875169d8ae5349/ovos_utils/plugins/stt.py#L18

**Comment by JarbasAl** [comment]
STT class moved to https://github.com/OpenVoiceOS/OVOS-plugin-manager
